### ISSUE TITLE
Move conditional milestone filtering to API

### ISSUE THREAD

**Issue by hannahkates** [NYCPlanning/deprecated-labs-zap-api#106]
Currently a lot of data handling, recoding, and filtering for milestones is happening in the front-end (here: https://github.com/NYCPlanning/labs-zap-search/blob/develop/app/components/project-milestone.js). To simplify future updates and better separate concerns, some of this functionality should be moved to the API instead.

Things to move:
- [x] Display name recoding
- [x] Date handling
- [x] Filtering which milestone dates to include based on project status (only filed or further along)
- [x] Milestones descriptions based on whether project is ULURP or not

**Comment by hannahkates** [comment]
Issues noted during implementation:
- "Filed" projects aren't labeled correctly in the 'dcp_publicstatus' field. Several of them have actually advanced into the public review process - these are showing up on the production site when they shouldn't be:
  - 2019Q0292
  - P2018K0108
  - 2019K0287
- Several "Filed" projects are over a decade old and listed below them are a bunch of projects that don't provide a date for sorting.
